services:
  portalarr:
    container_name: Portalarr
    build: .
    image: ghcr.io/plexd281knilb/portalarr:latest
    restart: unless-stopped
    user: root  # <--- Required to fix Unraid DB lock issues
    ports:
      - "3001:3000"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - DATABASE_URL=file:/app/data/dev.db
      - NODE_ENV=production
    volumes:
      # Unraid Appdata Mapping
      - /mnt/user/appdata/portalarr/data:/app/data
      
      # Read-only access to unraid shares for your glances/stats
      - /mnt/user:/mnt/user:ro
      - /mnt/remotes:/mnt/remotes:ro