import { MigrationInterface, QueryRunner } from 'typeorm';

export class MakeDownloadClientTypeNullable1789161267512 implements MigrationInterface {
  name = 'MakeDownloadClientTypeNullable1789161267512';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
            CREATE TABLE "temporary_settings" (
                "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL,
                "clientId" varchar,
                "applicationTitle" varchar NOT NULL DEFAULT ('Maintainerr'),
                "applicationUrl" varchar NOT NULL DEFAULT ('localhost'),
                "apikey" varchar,
                "locale" varchar NOT NULL DEFAULT ('en'),
                "plex_name" varchar,
                "plex_hostname" varchar,
                "plex_port" integer DEFAULT (32400),
                "plex_ssl" integer,
                "plex_auth_token" varchar,
                "collection_handler_job_cron" varchar NOT NULL DEFAULT ('0 0-23/12 * * *'),
                "rules_handler_job_cron" varchar NOT NULL DEFAULT ('0 0-23/8 * * *'),
                "tautulli_url" varchar,
                "tautulli_api_key" varchar,
                "media_server_type" varchar,
                "jellyfin_url" varchar,
                "jellyfin_api_key" varchar,
                "jellyfin_user_id" varchar,
                "jellyfin_server_name" varchar,
                "seerr_url" varchar,
                "seerr_api_key" varchar,
                "tmdb_api_key" varchar,
                "tvdb_api_key" varchar,
                "metadata_provider_preference" varchar NOT NULL DEFAULT ('tmdb_primary'),
                "plex_machine_id" varchar,
                "plex_manual_mode" integer DEFAULT (0),
                "emby_url" varchar,
                "emby_api_key" varchar,
                "emby_user_id" varchar,
                "emby_server_name" varchar,
                "streamystats_url" varchar,
                "download_client_url" varchar,
                "download_client_username" varchar,
                "download_client_password" varchar,
                "download_client_delete_data" boolean DEFAULT (1),
                "download_client_fallback_ratio" float NOT NULL DEFAULT (0.5),
                "radarr_tag_exclusions" boolean NOT NULL DEFAULT (0),
                "radarr_exclusion_tag" varchar NOT NULL DEFAULT ('dnd'),
                "radarr_untag_on_unexclude" boolean NOT NULL DEFAULT (0),
                "sonarr_tag_exclusions" boolean NOT NULL DEFAULT (0),
                "sonarr_exclusion_tag" varchar NOT NULL DEFAULT ('dnd'),
                "sonarr_untag_on_unexclude" boolean NOT NULL DEFAULT (0),
                "tracearr_url" varchar,
                "tracearr_api_key" varchar,
                "tracearr_server_id" varchar,
                "telemetryEnabled" boolean,
                "download_client_type" varchar NOT NULL DEFAULT ('qbittorrent')
            )
        `);
    await queryRunner.query(`
            INSERT INTO "temporary_settings"(
                    "id",
                    "clientId",
                    "applicationTitle",
                    "applicationUrl",
                    "apikey",
                    "locale",
                    "plex_name",
                    "plex_hostname",
                    "plex_port",
                    "plex_ssl",
                    "plex_auth_token",
                    "collection_handler_job_cron",
                    "rules_handler_job_cron",
                    "tautulli_url",
                    "tautulli_api_key",
                    "media_server_type",
                    "jellyfin_url",
                    "jellyfin_api_key",
                    "jellyfin_user_id",
                    "jellyfin_server_name",
                    "seerr_url",
                    "seerr_api_key",
                    "tmdb_api_key",
                    "tvdb_api_key",
                    "metadata_provider_preference",
                    "plex_machine_id",
                    "plex_manual_mode",
                    "emby_url",
                    "emby_api_key",
                    "emby_user_id",
                    "emby_server_name",
                    "streamystats_url",
                    "download_client_url",
                    "download_client_username",
                    "download_client_password",
                    "download_client_delete_data",
                    "download_client_fallback_ratio",
                    "radarr_tag_exclusions",
                    "radarr_exclusion_tag",
                    "radarr_untag_on_unexclude",
                    "sonarr_tag_exclusions",
                    "sonarr_exclusion_tag",
                    "sonarr_untag_on_unexclude",
                    "tracearr_url",
                    "tracearr_api_key",
                    "tracearr_server_id",
                    "telemetryEnabled",
                    "download_client_type"
                )
            SELECT "id",
                "clientId",
                "applicationTitle",
                "applicationUrl",
                "apikey",
                "locale",
                "plex_name",
                "plex_hostname",
                "plex_port",
                "plex_ssl",
                "plex_auth_token",
                "collection_handler_job_cron",
                "rules_handler_job_cron",
                "tautulli_url",
                "tautulli_api_key",
                "media_server_type",
                "jellyfin_url",
                "jellyfin_api_key",
                "jellyfin_user_id",
                "jellyfin_server_name",
                "seerr_url",
                "seerr_api_key",
                "tmdb_api_key",
                "tvdb_api_key",
                "metadata_provider_preference",
                "plex_machine_id",
                "plex_manual_mode",
                "emby_url",
                "emby_api_key",
                "emby_user_id",
                "emby_server_name",
                "streamystats_url",
                "download_client_url",
                "download_client_username",
                "download_client_password",
                "download_client_delete_data",
                "download_client_fallback_ratio",
                "radarr_tag_exclusions",
                "radarr_exclusion_tag",
                "radarr_untag_on_unexclude",
                "sonarr_tag_exclusions",
                "sonarr_exclusion_tag",
                "sonarr_untag_on_unexclude",
                "tracearr_url",
                "tracearr_api_key",
                "tracearr_server_id",
                "telemetryEnabled",
                "download_client_type"
            FROM "settings"
        `);
    await queryRunner.query(`
            DROP TABLE "settings"
        `);
    await queryRunner.query(`
            ALTER TABLE "temporary_settings"
                RENAME TO "settings"
        `);
    await queryRunner.query(`
            CREATE TABLE "temporary_settings" (
                "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL,
                "clientId" varchar,
                "applicationTitle" varchar NOT NULL DEFAULT ('Maintainerr'),
                "applicationUrl" varchar NOT NULL DEFAULT ('localhost'),
                "apikey" varchar,
                "locale" varchar NOT NULL DEFAULT ('en'),
                "plex_name" varchar,
                "plex_hostname" varchar,
                "plex_port" integer DEFAULT (32400),
                "plex_ssl" integer,
                "plex_auth_token" varchar,
                "collection_handler_job_cron" varchar NOT NULL DEFAULT ('0 0-23/12 * * *'),
                "rules_handler_job_cron" varchar NOT NULL DEFAULT ('0 0-23/8 * * *'),
                "tautulli_url" varchar,
                "tautulli_api_key" varchar,
                "media_server_type" varchar,
                "jellyfin_url" varchar,
                "jellyfin_api_key" varchar,
                "jellyfin_user_id" varchar,
                "jellyfin_server_name" varchar,
                "seerr_url" varchar,
                "seerr_api_key" varchar,
                "tmdb_api_key" varchar,
                "tvdb_api_key" varchar,
                "metadata_provider_preference" varchar NOT NULL DEFAULT ('tmdb_primary'),
                "plex_machine_id" varchar,
                "plex_manual_mode" integer DEFAULT (0),
                "emby_url" varchar,
                "emby_api_key" varchar,
                "emby_user_id" varchar,
                "emby_server_name" varchar,
                "streamystats_url" varchar,
                "download_client_url" varchar,
                "download_client_username" varchar,
                "download_client_password" varchar,
                "download_client_delete_data" boolean DEFAULT (1),
                "download_client_fallback_ratio" float NOT NULL DEFAULT (0.5),
                "radarr_tag_exclusions" boolean NOT NULL DEFAULT (0),
                "radarr_exclusion_tag" varchar NOT NULL DEFAULT ('dnd'),
                "radarr_untag_on_unexclude" boolean NOT NULL DEFAULT (0),
                "sonarr_tag_exclusions" boolean NOT NULL DEFAULT (0),
                "sonarr_exclusion_tag" varchar NOT NULL DEFAULT ('dnd'),
                "sonarr_untag_on_unexclude" boolean NOT NULL DEFAULT (0),
                "tracearr_url" varchar,
                "tracearr_api_key" varchar,
                "tracearr_server_id" varchar,
                "telemetryEnabled" boolean,
                "download_client_type" varchar
            )
        `);
    await queryRunner.query(`
            INSERT INTO "temporary_settings"(
                    "id",
                    "clientId",
                    "applicationTitle",
                    "applicationUrl",
                    "apikey",
                    "locale",
                    "plex_name",
                    "plex_hostname",
                    "plex_port",
                    "plex_ssl",
                    "plex_auth_token",
                    "collection_handler_job_cron",
                    "rules_handler_job_cron",
                    "tautulli_url",
                    "tautulli_api_key",
                    "media_server_type",
                    "jellyfin_url",
                    "jellyfin_api_key",
                    "jellyfin_user_id",
                    "jellyfin_server_name",
                    "seerr_url",
                    "seerr_api_key",
                    "tmdb_api_key",
                    "tvdb_api_key",
                    "metadata_provider_preference",
                    "plex_machine_id",
                    "plex_manual_mode",
                    "emby_url",
                    "emby_api_key",
                    "emby_user_id",
                    "emby_server_name",
                    "streamystats_url",
                    "download_client_url",
                    "download_client_username",
                    "download_client_password",
                    "download_client_delete_data",
                    "download_client_fallback_ratio",
                    "radarr_tag_exclusions",
                    "radarr_exclusion_tag",
                    "radarr_untag_on_unexclude",
                    "sonarr_tag_exclusions",
                    "sonarr_exclusion_tag",
                    "sonarr_untag_on_unexclude",
                    "tracearr_url",
                    "tracearr_api_key",
                    "tracearr_server_id",
                    "telemetryEnabled",
                    "download_client_type"
                )
            SELECT "id",
                "clientId",
                "applicationTitle",
                "applicationUrl",
                "apikey",
                "locale",
                "plex_name",
                "plex_hostname",
                "plex_port",
                "plex_ssl",
                "plex_auth_token",
                "collection_handler_job_cron",
                "rules_handler_job_cron",
                "tautulli_url",
                "tautulli_api_key",
                "media_server_type",
                "jellyfin_url",
                "jellyfin_api_key",
                "jellyfin_user_id",
                "jellyfin_server_name",
                "seerr_url",
                "seerr_api_key",
                "tmdb_api_key",
                "tvdb_api_key",
                "metadata_provider_preference",
                "plex_machine_id",
                "plex_manual_mode",
                "emby_url",
                "emby_api_key",
                "emby_user_id",
                "emby_server_name",
                "streamystats_url",
                "download_client_url",
                "download_client_username",
                "download_client_password",
                "download_client_delete_data",
                "download_client_fallback_ratio",
                "radarr_tag_exclusions",
                "radarr_exclusion_tag",
                "radarr_untag_on_unexclude",
                "sonarr_tag_exclusions",
                "sonarr_exclusion_tag",
                "sonarr_untag_on_unexclude",
                "tracearr_url",
                "tracearr_api_key",
                "tracearr_server_id",
                "telemetryEnabled",
                "download_client_type"
            FROM "settings"
        `);
    await queryRunner.query(`
            DROP TABLE "settings"
        `);
    await queryRunner.query(`
            ALTER TABLE "temporary_settings"
                RENAME TO "settings"
        `);

    // Only an install that already had a client configured keeps the
    // earlier qBittorrent backfill; everything else reads as no client.
    await queryRunner.manager
      .createQueryBuilder()
      .update('settings')
      .set({ download_client_type: null })
      .where('download_client_url IS NULL')
      .execute();
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // The NOT NULL rebuild below rejects a null type, so restore the value
    // the column carried before.
    await queryRunner.manager
      .createQueryBuilder()
      .update('settings')
      .set({ download_client_type: 'qbittorrent' })
      .where('download_client_type IS NULL')
      .execute();
    await queryRunner.query(`
            ALTER TABLE "settings"
                RENAME TO "temporary_settings"
        `);
    await queryRunner.query(`
            CREATE TABLE "settings" (
                "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL,
                "clientId" varchar,
                "applicationTitle" varchar NOT NULL DEFAULT ('Maintainerr'),
                "applicationUrl" varchar NOT NULL DEFAULT ('localhost'),
                "apikey" varchar,
                "locale" varchar NOT NULL DEFAULT ('en'),
                "plex_name" varchar,
                "plex_hostname" varchar,
                "plex_port" integer DEFAULT (32400),
                "plex_ssl" integer,
                "plex_auth_token" varchar,
                "collection_handler_job_cron" varchar NOT NULL DEFAULT ('0 0-23/12 * * *'),
                "rules_handler_job_cron" varchar NOT NULL DEFAULT ('0 0-23/8 * * *'),
                "tautulli_url" varchar,
                "tautulli_api_key" varchar,
                "media_server_type" varchar,
                "jellyfin_url" varchar,
                "jellyfin_api_key" varchar,
                "jellyfin_user_id" varchar,
                "jellyfin_server_name" varchar,
                "seerr_url" varchar,
                "seerr_api_key" varchar,
                "tmdb_api_key" varchar,
                "tvdb_api_key" varchar,
                "metadata_provider_preference" varchar NOT NULL DEFAULT ('tmdb_primary'),
                "plex_machine_id" varchar,
                "plex_manual_mode" integer DEFAULT (0),
                "emby_url" varchar,
                "emby_api_key" varchar,
                "emby_user_id" varchar,
                "emby_server_name" varchar,
                "streamystats_url" varchar,
                "download_client_url" varchar,
                "download_client_username" varchar,
                "download_client_password" varchar,
                "download_client_delete_data" boolean DEFAULT (1),
                "download_client_fallback_ratio" float NOT NULL DEFAULT (0.5),
                "radarr_tag_exclusions" boolean NOT NULL DEFAULT (0),
                "radarr_exclusion_tag" varchar NOT NULL DEFAULT ('dnd'),
                "radarr_untag_on_unexclude" boolean NOT NULL DEFAULT (0),
                "sonarr_tag_exclusions" boolean NOT NULL DEFAULT (0),
                "sonarr_exclusion_tag" varchar NOT NULL DEFAULT ('dnd'),
                "sonarr_untag_on_unexclude" boolean NOT NULL DEFAULT (0),
                "tracearr_url" varchar,
                "tracearr_api_key" varchar,
                "tracearr_server_id" varchar,
                "telemetryEnabled" boolean,
                "download_client_type" varchar NOT NULL DEFAULT ('qbittorrent')
            )
        `);
    await queryRunner.query(`
            INSERT INTO "settings"(
                    "id",
                    "clientId",
                    "applicationTitle",
                    "applicationUrl",
                    "apikey",
                    "locale",
                    "plex_name",
                    "plex_hostname",
                    "plex_port",
                    "plex_ssl",
                    "plex_auth_token",
                    "collection_handler_job_cron",
                    "rules_handler_job_cron",
                    "tautulli_url",
                    "tautulli_api_key",
                    "media_server_type",
                    "jellyfin_url",
                    "jellyfin_api_key",
                    "jellyfin_user_id",
                    "jellyfin_server_name",
                    "seerr_url",
                    "seerr_api_key",
                    "tmdb_api_key",
                    "tvdb_api_key",
                    "metadata_provider_preference",
                    "plex_machine_id",
                    "plex_manual_mode",
                    "emby_url",
                    "emby_api_key",
                    "emby_user_id",
                    "emby_server_name",
                    "streamystats_url",
                    "download_client_url",
                    "download_client_username",
                    "download_client_password",
                    "download_client_delete_data",
                    "download_client_fallback_ratio",
                    "radarr_tag_exclusions",
                    "radarr_exclusion_tag",
                    "radarr_untag_on_unexclude",
                    "sonarr_tag_exclusions",
                    "sonarr_exclusion_tag",
                    "sonarr_untag_on_unexclude",
                    "tracearr_url",
                    "tracearr_api_key",
                    "tracearr_server_id",
                    "telemetryEnabled",
                    "download_client_type"
                )
            SELECT "id",
                "clientId",
                "applicationTitle",
                "applicationUrl",
                "apikey",
                "locale",
                "plex_name",
                "plex_hostname",
                "plex_port",
                "plex_ssl",
                "plex_auth_token",
                "collection_handler_job_cron",
                "rules_handler_job_cron",
                "tautulli_url",
                "tautulli_api_key",
                "media_server_type",
                "jellyfin_url",
                "jellyfin_api_key",
                "jellyfin_user_id",
                "jellyfin_server_name",
                "seerr_url",
                "seerr_api_key",
                "tmdb_api_key",
                "tvdb_api_key",
                "metadata_provider_preference",
                "plex_machine_id",
                "plex_manual_mode",
                "emby_url",
                "emby_api_key",
                "emby_user_id",
                "emby_server_name",
                "streamystats_url",
                "download_client_url",
                "download_client_username",
                "download_client_password",
                "download_client_delete_data",
                "download_client_fallback_ratio",
                "radarr_tag_exclusions",
                "radarr_exclusion_tag",
                "radarr_untag_on_unexclude",
                "sonarr_tag_exclusions",
                "sonarr_exclusion_tag",
                "sonarr_untag_on_unexclude",
                "tracearr_url",
                "tracearr_api_key",
                "tracearr_server_id",
                "telemetryEnabled",
                "download_client_type"
            FROM "temporary_settings"
        `);
    await queryRunner.query(`
            DROP TABLE "temporary_settings"
        `);
    await queryRunner.query(`
            ALTER TABLE "settings"
                RENAME TO "temporary_settings"
        `);
    await queryRunner.query(`
            CREATE TABLE "settings" (
                "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL,
                "clientId" varchar,
                "applicationTitle" varchar NOT NULL DEFAULT ('Maintainerr'),
                "applicationUrl" varchar NOT NULL DEFAULT ('localhost'),
                "apikey" varchar,
                "locale" varchar NOT NULL DEFAULT ('en'),
                "plex_name" varchar,
                "plex_hostname" varchar,
                "plex_port" integer DEFAULT (32400),
                "plex_ssl" integer,
                "plex_auth_token" varchar,
                "collection_handler_job_cron" varchar NOT NULL DEFAULT ('0 0-23/12 * * *'),
                "rules_handler_job_cron" varchar NOT NULL DEFAULT ('0 0-23/8 * * *'),
                "tautulli_url" varchar,
                "tautulli_api_key" varchar,
                "media_server_type" varchar,
                "jellyfin_url" varchar,
                "jellyfin_api_key" varchar,
                "jellyfin_user_id" varchar,
                "jellyfin_server_name" varchar,
                "seerr_url" varchar,
                "seerr_api_key" varchar,
                "tmdb_api_key" varchar,
                "tvdb_api_key" varchar,
                "metadata_provider_preference" varchar NOT NULL DEFAULT ('tmdb_primary'),
                "plex_machine_id" varchar,
                "plex_manual_mode" integer DEFAULT (0),
                "emby_url" varchar,
                "emby_api_key" varchar,
                "emby_user_id" varchar,
                "emby_server_name" varchar,
                "streamystats_url" varchar,
                "download_client_url" varchar,
                "download_client_username" varchar,
                "download_client_password" varchar,
                "download_client_delete_data" boolean DEFAULT (1),
                "download_client_fallback_ratio" float NOT NULL DEFAULT (0.5),
                "radarr_tag_exclusions" boolean NOT NULL DEFAULT (0),
                "radarr_exclusion_tag" varchar NOT NULL DEFAULT ('dnd'),
                "radarr_untag_on_unexclude" boolean NOT NULL DEFAULT (0),
                "sonarr_tag_exclusions" boolean NOT NULL DEFAULT (0),
                "sonarr_exclusion_tag" varchar NOT NULL DEFAULT ('dnd'),
                "sonarr_untag_on_unexclude" boolean NOT NULL DEFAULT (0),
                "tracearr_url" varchar,
                "tracearr_api_key" varchar,
                "tracearr_server_id" varchar,
                "telemetryEnabled" boolean,
                "download_client_type" varchar NOT NULL DEFAULT ('qbittorrent')
            )
        `);
    await queryRunner.query(`
            INSERT INTO "settings"(
                    "id",
                    "clientId",
                    "applicationTitle",
                    "applicationUrl",
                    "apikey",
                    "locale",
                    "plex_name",
                    "plex_hostname",
                    "plex_port",
                    "plex_ssl",
                    "plex_auth_token",
                    "collection_handler_job_cron",
                    "rules_handler_job_cron",
                    "tautulli_url",
                    "tautulli_api_key",
                    "media_server_type",
                    "jellyfin_url",
                    "jellyfin_api_key",
                    "jellyfin_user_id",
                    "jellyfin_server_name",
                    "seerr_url",
                    "seerr_api_key",
                    "tmdb_api_key",
                    "tvdb_api_key",
                    "metadata_provider_preference",
                    "plex_machine_id",
                    "plex_manual_mode",
                    "emby_url",
                    "emby_api_key",
                    "emby_user_id",
                    "emby_server_name",
                    "streamystats_url",
                    "download_client_url",
                    "download_client_username",
                    "download_client_password",
                    "download_client_delete_data",
                    "download_client_fallback_ratio",
                    "radarr_tag_exclusions",
                    "radarr_exclusion_tag",
                    "radarr_untag_on_unexclude",
                    "sonarr_tag_exclusions",
                    "sonarr_exclusion_tag",
                    "sonarr_untag_on_unexclude",
                    "tracearr_url",
                    "tracearr_api_key",
                    "tracearr_server_id",
                    "telemetryEnabled",
                    "download_client_type"
                )
            SELECT "id",
                "clientId",
                "applicationTitle",
                "applicationUrl",
                "apikey",
                "locale",
                "plex_name",
                "plex_hostname",
                "plex_port",
                "plex_ssl",
                "plex_auth_token",
                "collection_handler_job_cron",
                "rules_handler_job_cron",
                "tautulli_url",
                "tautulli_api_key",
                "media_server_type",
                "jellyfin_url",
                "jellyfin_api_key",
                "jellyfin_user_id",
                "jellyfin_server_name",
                "seerr_url",
                "seerr_api_key",
                "tmdb_api_key",
                "tvdb_api_key",
                "metadata_provider_preference",
                "plex_machine_id",
                "plex_manual_mode",
                "emby_url",
                "emby_api_key",
                "emby_user_id",
                "emby_server_name",
                "streamystats_url",
                "download_client_url",
                "download_client_username",
                "download_client_password",
                "download_client_delete_data",
                "download_client_fallback_ratio",
                "radarr_tag_exclusions",
                "radarr_exclusion_tag",
                "radarr_untag_on_unexclude",
                "sonarr_tag_exclusions",
                "sonarr_exclusion_tag",
                "sonarr_untag_on_unexclude",
                "tracearr_url",
                "tracearr_api_key",
                "tracearr_server_id",
                "telemetryEnabled",
                "download_client_type"
            FROM "temporary_settings"
        `);
    await queryRunner.query(`
            DROP TABLE "temporary_settings"
        `);
  }
}
