import RadarrAPI from '@server/api/servarr/radarr';
import SonarrAPI from '@server/api/servarr/sonarr';
import type { CollectionItem } from '@server/lib/collections/core/types';
import type {
  CollectionConfig,
  RadarrSettings,
  SonarrSettings,
} from '@server/lib/settings';
import { getSettings } from '@server/lib/settings';
import logger from '@server/logger';
import {
  getAutoGeneratedRadarrTagIds,
  getAutoGeneratedSonarrTagIds,
  type TagSource,
} from './ArrTagUtils';

/**
 * Service for applying tags to existing items in Radarr/Sonarr during collection sync
 *
 * When a collection sync identifies items that exist in Plex (CollectionItem[]),
 * this service can apply the collection's configured tags to those items in Radarr/Sonarr.
 * This is controlled by the tagExistingItems setting on each Radarr/Sonarr server.
 *
 * Tags applied include:
 * - Auto-generated collection tags (based on tagRequestsMode)
 * - Collection-specific override tags (which are pre-filled with server defaults
 *   when the user creates a collection, so server defaults are already included)
 */
class ExistingItemTagService {
  /**
   * Apply configured tags to existing items in Radarr/Sonarr
   *
   * @param items - Collection items that exist in Plex
   * @param config - Collection configuration with tag settings
   * @param source - Source type for tag generation
   */
  public async tagExistingItems(
    items: CollectionItem[],
    config: CollectionConfig,
    source: string
  ): Promise<void> {
    const settings = getSettings();

    // Determine which server and tags to use based on download mode
    const downloadMode = config.downloadMode || 'overseerr';
    const isDirectMode = downloadMode === 'direct';

    let radarrServerId: number | undefined;
    let sonarrServerId: number | undefined;
    let radarrCollectionTags: number[];
    let sonarrCollectionTags: number[];

    if (isDirectMode) {
      radarrServerId = config.directDownloadRadarrServerId;
      sonarrServerId = config.directDownloadSonarrServerId;
      radarrCollectionTags = config.directDownloadRadarrTags || [];
      sonarrCollectionTags = config.directDownloadSonarrTags || [];
    } else {
      // Overseerr mode - use overseerr server and tag settings
      radarrServerId = config.overseerrRadarrServerId;
      sonarrServerId = config.overseerrSonarrServerId;
      radarrCollectionTags = config.overseerrRadarrTags || [];
      sonarrCollectionTags = config.overseerrSonarrTags || [];
    }

    // Split items by media type
    const movieItems = items.filter(
      (item) => item.type === 'movie' && item.tmdbId
    );
    const tvItems = items.filter((item) => item.type === 'tv' && item.tvdbId);

    // Process Radarr tags for movies
    if (movieItems.length > 0) {
      await this.tagMoviesInRadarr(
        movieItems,
        radarrServerId,
        settings.radarr,
        config,
        source as TagSource,
        radarrCollectionTags
      );
    }

    // Process Sonarr tags for TV shows
    if (tvItems.length > 0) {
      await this.tagSeriesInSonarr(
        tvItems,
        sonarrServerId,
        settings.sonarr,
        config,
        source as TagSource,
        sonarrCollectionTags
      );
    }
  }

  /**
   * Apply tags to movies in Radarr
   */
  private async tagMoviesInRadarr(
    items: CollectionItem[],
    serverId: number | undefined,
    radarrServers: RadarrSettings[],
    config: CollectionConfig,
    source: TagSource,
    collectionOverrideTags: number[]
  ): Promise<void> {
    // Find the target Radarr server
    const server = serverId
      ? radarrServers.find((s) => s.id === serverId)
      : radarrServers.find((s) => s.isDefault) || radarrServers[0];

    if (!server) {
      logger.debug('No Radarr server configured for tagging existing items', {
        label: 'ExistingItemTagService',
        collection: config.name,
      });
      return;
    }

    // Check if tagExistingItems is enabled for this server
    if (!server.tagExistingItems) {
      logger.debug('tagExistingItems not enabled for Radarr server, skipping', {
        label: 'ExistingItemTagService',
        server: server.name,
        collection: config.name,
      });
      return;
    }

    try {
      // Get tags to apply: auto-generated + collection overrides
      // NOTE: Server defaults are NOT added separately because the collection override
      // tags are pre-filled with server defaults when the user creates a collection.
      // Adding them again would re-add tags the user explicitly removed.
      const autoTagIds = await getAutoGeneratedRadarrTagIds(
        server,
        config,
        source
      );
      const tagIds = [...new Set([...autoTagIds, ...collectionOverrideTags])];

      if (tagIds.length === 0) {
        logger.debug('No tags to apply for Radarr', {
          label: 'ExistingItemTagService',
          collection: config.name,
        });
        return;
      }

      const radarrAPI = new RadarrAPI({
        url: RadarrAPI.buildUrl(server, '/api/v3'),
        apiKey: server.apiKey,
      });

      // Get all movies from Radarr to build tmdbId -> id map
      const allMovies = await radarrAPI.getMovies();
      const tmdbToIdMap = new Map<number, number>();
      for (const movie of allMovies) {
        tmdbToIdMap.set(movie.tmdbId, movie.id);
      }

      // Find Radarr IDs for our collection items
      const movieIds: number[] = [];
      for (const item of items) {
        if (item.tmdbId) {
          const radarrId = tmdbToIdMap.get(item.tmdbId);
          if (radarrId) {
            movieIds.push(radarrId);
          }
        }
      }

      if (movieIds.length === 0) {
        logger.debug('No matching movies found in Radarr for tagging', {
          label: 'ExistingItemTagService',
          collection: config.name,
          itemCount: items.length,
        });
        return;
      }

      // Bulk add tags
      await radarrAPI.bulkAddTags(movieIds, tagIds);

      logger.info(
        `Tagged ${movieIds.length} existing movies in Radarr for collection "${config.name}"`,
        {
          label: 'ExistingItemTagService',
          source,
          collection: config.name,
          server: server.name,
          movieCount: movieIds.length,
          tagIds,
        }
      );
    } catch (error) {
      logger.error(
        `Failed to tag existing movies in Radarr for collection "${config.name}"`,
        {
          label: 'ExistingItemTagService',
          source,
          collection: config.name,
          error: error instanceof Error ? error.message : String(error),
        }
      );
    }
  }

  /**
   * Apply tags to TV series in Sonarr
   */
  private async tagSeriesInSonarr(
    items: CollectionItem[],
    serverId: number | undefined,
    sonarrServers: SonarrSettings[],
    config: CollectionConfig,
    source: TagSource,
    collectionOverrideTags: number[]
  ): Promise<void> {
    // Find the target Sonarr server
    const server = serverId
      ? sonarrServers.find((s) => s.id === serverId)
      : sonarrServers.find((s) => s.isDefault) || sonarrServers[0];

    if (!server) {
      logger.debug('No Sonarr server configured for tagging existing items', {
        label: 'ExistingItemTagService',
        collection: config.name,
      });
      return;
    }

    // Check if tagExistingItems is enabled for this server
    if (!server.tagExistingItems) {
      logger.debug('tagExistingItems not enabled for Sonarr server, skipping', {
        label: 'ExistingItemTagService',
        server: server.name,
        collection: config.name,
      });
      return;
    }

    try {
      // Get tags to apply: auto-generated + collection overrides
      // NOTE: Server defaults are NOT added separately - see Radarr comment above
      const autoTagIds = await getAutoGeneratedSonarrTagIds(
        server,
        config,
        source
      );
      const tagIds = [...new Set([...autoTagIds, ...collectionOverrideTags])];

      if (tagIds.length === 0) {
        logger.debug('No tags to apply for Sonarr', {
          label: 'ExistingItemTagService',
          collection: config.name,
        });
        return;
      }

      const sonarrAPI = new SonarrAPI({
        url: SonarrAPI.buildUrl(server, '/api/v3'),
        apiKey: server.apiKey,
      });

      // Get all series from Sonarr to build tvdbId -> id map
      const allSeries = await sonarrAPI.getSeries();
      const tvdbToIdMap = new Map<number, number>();
      for (const series of allSeries) {
        if (series.id) {
          tvdbToIdMap.set(series.tvdbId, series.id);
        }
      }

      // Find Sonarr IDs for our collection items
      const seriesIds: number[] = [];
      for (const item of items) {
        if (item.tvdbId) {
          const sonarrId = tvdbToIdMap.get(item.tvdbId);
          if (sonarrId) {
            seriesIds.push(sonarrId);
          }
        }
      }

      if (seriesIds.length === 0) {
        logger.debug('No matching series found in Sonarr for tagging', {
          label: 'ExistingItemTagService',
          collection: config.name,
          itemCount: items.length,
        });
        return;
      }

      // Bulk add tags
      await sonarrAPI.bulkAddTags(seriesIds, tagIds);

      logger.info(
        `Tagged ${seriesIds.length} existing series in Sonarr for collection "${config.name}"`,
        {
          label: 'ExistingItemTagService',
          source,
          collection: config.name,
          server: server.name,
          seriesCount: seriesIds.length,
          tagIds,
        }
      );
    } catch (error) {
      logger.error(
        `Failed to tag existing series in Sonarr for collection "${config.name}"`,
        {
          label: 'ExistingItemTagService',
          source,
          collection: config.name,
          error: error instanceof Error ? error.message : String(error),
        }
      );
    }
  }
}

export const existingItemTagService = new ExistingItemTagService();
export default existingItemTagService;
